language: node_js

node_js:
  - "0.12"
  - "2"
  - "4"
  - "5"

services:
  - mongodb
  - redis-server

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

env:
  - GCLOUD_PROJECT_NUM=0

after_success:
  - ./bin/run-coverage.sh
