# Test against this version of Node.js
environment:
  matrix:
  # node.js
  - nodejs_version: "6"
  - nodejs_version: "8"
  - nodejs_version: "10"

cache:
  - src/plugins/types -> src/plugins/types/index.d.ts
  - node_modules -> package-lock.json, package.json

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - SET GCLOUD_PROJECT=0
  - SET TRACE_TEST_EXCLUDE_INTEGRATION=1

# Post-install test scripts.
test_script:
  # install modules
  - npm install
  # check code style and linting
  - npm run check
  # compile the code
  - npm run compile
  # check that installing this module is OK
  - npm run check-install
  # initialize test fixtures
  - npm run init-test-fixtures
  # run tests
  - npm run unit-test

# Don't actually build using MSBuild
build: off
